### ISSUE TITLE
Roadmap / v2.0.0

### ISSUE THREAD

**Issue by timcraft** [Vonage/vonage-ruby-sdk#16]
Changes planned for v2.0.0:
- [x] use webmock instead of mocha
- [x] drop support for Ruby 1.8.7
- [x] remove deprecated json functionality
- [x] remove faux dependency
- [x] remove key/secret args in favour of using options hash
- [x] eliminate Nexmo::Response class in favour of raising exceptions
- [x] add US Shared Short Codes API methods
- [x] add USSD API methods
- [x] add Voice API methods

Feedback and other suggestions welcome.

**Comment by adambishop** [comment]
Any plans to include Nexmo's USSD suport?

**Comment by timcraft** [comment]
@adambishop No plans, but should be possible to add that.

**Comment by adambishop** [comment]
OK thanks for this.

**Comment by auzroz** [comment]
Would it be possible to add Short Code support?

**Comment by timcraft** [comment]
@auzroz Should be, added it to the list.
